name = "idyab"
main = "index.js"
compatibility_date = "2026-08-01"

# اتصال به دیتابیس D1 (برای ذخیره نامحدود کاربران)
[[d1_databases]]
binding = "DB"                     # نام binding که در کد index.js استفاده شده
database_name = "idyab-db"         # نام دیتابیسی که در کلودفلر می‌سازی
database_id = "{807aeb3b-027e-4d26-966c-96bff28fb709}"   # شناسه دیتابیس (از داشبورد کلودفلر کپی کن)

# متغیرهای غیرحساس (فقط برای وب‌هوک)
[vars]
WEBHOOK_SECRET = "{WEBHOOK_SECRET}"  # یک رشته تصادفی طولانی (مثلاً 32 کاراکتر)